{% block subject %}[{{ guest.system_company.name }}] Partners license issued{% endblock %}
{% block content %}
{% filter markdown %}
Hi {{ c.first_name }},

New **{{ order.title }}** was created.

Invoice for this license will be issued on {{ partner.next_invoice_date|date }}

Login to members area: {{ 'login'|link }}?email={{ c.email }}   
Manage order: {{ 'service/manage'|link }}/{{ order.id }}     

Reference order #{{ order.id }}

{{ guest.system_company.signature }}

{% endfilter %}
{% endblock %}
