{% block subject %}[{{ guest.system_company.name }}] {{ order.title }} unsuspended{% endblock %}
{% block content %}
{% filter markdown %}

Hello {{ c.first_name }} {{ c.last_name }},

Your *{{ order.title }}* was unsuspended 

Login to members area: {{ 'login'|link }}?email={{ c.email }}   
Manage order: {{ 'service/manage'|link }}/{{ order.id }}    

{{ guest.system_company.signature }}

{% endfilter %}
{% endblock %}