{% block subject %}[{{ guest.system_company.name }}] {{ order.title }} renewed{% endblock %}
{% block content %}
{% filter markdown %}

Hello {{ c.first_name }} {{ c.last_name }},

Your **{{ order.title }}** was renewed.

{% if order.expires_at %}

Next renewal date: {{ order.expires_at|date }}

{% endif %}

Login to members area: {{ 'login'|link }}?email={{ c.email }}   
Manage order: {{ 'service/manage'|link }}/{{ order.id }}     

{{ guest.system_company.signature }}

{% endfilter %}
{% endblock %}