{% block subject %}You have joined affiliate program{% endblock %}
{% block content %}
{% filter markdown %}
Hi {{ c.first_name }},

Thank you for joining affiliate program.

Your refferal link is: {{ referral_link }}

Online reports detailing traffic, sales and commission earned can be accessed
at {{ 'affiliate/stats'|link }} 

Banners, text links and other creative materials are also available there.
All links contain a unique code to track visitors and credit your account.

We'll pay you commission for every new order referred from your 
website, blog, email or any other compaign.

{{ guest.system_company.name }} affiliate marketing program is a great opportunity 
to increase your online revenue. Place a banner or text link to {{ referral_link }}
on your website, blog or within your email campaign and earn commission every 
time a visitor clicks on that link and successfully enrolls in the {{ guest.system_company.name }}

{{ guest.system_company.signature }}

{% endfilter %}
{% endblock %}
